services:
    db-user:
      image: postgres:16
      container_name: meu-postgres
      environment:
        POSTGRES_DB: usuario
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: senha123
      networks: 
        - arq-network
      ports:
        - "5432:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data

    keycloak-service:
      image: quay.io/keycloak/keycloak:24.0
      container_name: keycloak
      command: start-dev --http-port=8080 --import-realm
      restart: always
      depends_on:
        - db-user
      environment:
        KC_DB: postgres
        KC_DB_URL_HOST: db-user
        KC_DB_URL_PORT: 5432
        KC_DB_URL_DATABASE: usuario
        KC_DB_USERNAME: postgres
        KC_DB_PASSWORD: senha123
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin
        KC_HTTP_ENABLED: "true"
      ports:
        - "8081:8080"
      networks:
        - arq-network
      volumes:
        - ./realm-export.json:/opt/keycloak/data/import/realm.json

    jaeger:
      image: jaegertracing/all-in-one:latest
      container_name: jaeger-identity
      ports:
        - "16686:16686"
        - "4317:4317"
        - "4318:4318"
      networks:
        - arq-network
      environment:
        COLLECTOR_OTLP_ENABLED: "true"
      volumes:
        - ./data/jaeger:/badger

    ## 
    ms-user:
      image: ${DOCKER_REGISTRY-}ms-user
      build:
        context: ./identity-users
        dockerfile: Dockerfile
      ports: 
        - "9009:9009"
      networks:
        - arq-network
volumes:
  postgres_data:

networks:
  arq-network:
    driver: bridge