spring.datasource.url=jdbc:postgresql://localhost:5432/books-service
spring.datasource.username=postgres
spring.datasource.password=postgres@local

# Deixado dessa forma para testes
spring.jpa.hibernate.ddl-auto=update

spring.main.allow-bean-definition-overriding=true
spring.main.web-application-type=servlet

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://keycloak-service:8093/realms/master

#Observabilidade
management.otlp.metrics.export.enabled=false
management.tracing.sampling.probability=1
management.tracing.propagation.type=w3c

management.opentelemetry.tracing.export.otlp.endpoint=http://jaeger:4318/v1/traces

logging.include-application-name=false