services:
  db-keycloak:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres@local
      POSTGRES_DB: keycloak
    ports:
      - "5434:5432"
    networks:
      - keycloak-network

  keycloak-service:
    image: quay.io/keycloak/keycloak:24.0
    container_name: keycloak
    command: start-dev --http-port=8080 --import-realm
    restart: always
    depends_on:
      - db-keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: db-keycloak
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres@local
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME: localhost
      KC_HTTP_ENABLED: "true"
    ports:
      - "8081:8080"
    networks:
      - keycloak-network
    volumes:
      - ./realm-export.json:/opt/keycloak/data/import/realm.json

  postgres:
    image: postgres:16
    container_name: meu-postgres
    environment:
      POSTGRES_DB: usuario
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger-identity
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
    volumes:
      - ./data/jaeger:/badger

volumes:
  postgres_data:

networks:
  keycloak-network:
    driver: bridge